#ifndef XMLTOFLATLISTCONVERTER_TEST_XMLTOFLATLISTCONVERTER_HPP
#define XMLTOFLATLISTCONVERTER_TEST_XMLTOFLATLISTCONVERTER_HPP

#include "api.hpp"

namespace xtfl
{

XMLTOFLATLISTCONVERTER_API
void test_runAll();

} // !xtfl


#endif // XMLTOFLATLISTCONVERTER_TEST_XMLTOFLATLISTCONVERTER_HPP
